version: 2.1

orbs:
  win: circleci/windows@2.2.0

commands:
  run-cibuildwheel:
    parameters:
      cibw-version:
        type: string
        default: 2.11.2
    steps:
      - run:
          name: run cibuildwheel
          shell: bash -eo pipefail
          command: |
            if [[ $OS == Windows_NT ]]; then
              python -m pip install --user cibuildwheel==<< parameters.cibw-version >>
              python -m cibuildwheel --output-dir dist
            else
              python3 -m pip install --user cibuildwheel==<< parameters.cibw-version >>
              python3 -m cibuildwheel --output-dir dist
            fi

      - store_artifacts: &store-artifacts
          path: ./dist
      - persist_to_workspace: &persist-to-workspace
          root: ./dist/
          paths: .

environment: &global-environment
  PIP_PROGRESS_BAR: 'off'

jobs:
  build-and-test-linux:
    parameters:
      python-version:
        type: string

    docker:
      - image: cimg/python:3.9

    environment:
      <<: *global-environment
      CIBW_PROJECT_REQUIRES_PYTHON: ~=<< parameters.python-version>>
      CIBW_ARCHS_LINUX: x86_64

    steps:
      - checkout
      - setup_remote_docker
      - run-cibuildwheel

  build-and-test-linux-aarch64:
    parameters:
      python-version:
        type: string

    machine:
      image: ubuntu-2004:202101-01

    resource_class: arm.medium

    environment:
      <<: *global-environment
      CIBW_PROJECT_REQUIRES_PYTHON: ~=<< parameters.python-version>>
      CIBW_ARCHS_LINUX: aarch64

    steps:
      - checkout
      - run-cibuildwheel

  build-and-test-osx:
    parameters:
      python-version:
        type: string
      cibw-arch:
        type: string

    macos:
      xcode: 12.5.1

    environment:
      <<: *global-environment
      CIBW_PROJECT_REQUIRES_PYTHON: ~=<< parameters.python-version>>
      CIBW_ARCHS_MACOS: << parameters.cibw-arch >>

    steps:
      - checkout
      - run-cibuildwheel

  build-sdist:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - run:
          name: build sdist
          command: |
            python -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            python dwave/gate/simulator/operation_generation.py
            python setup.py sdist -d ./dist
      - store_artifacts: *store-artifacts
      - persist_to_workspace: *persist-to-workspace

  build-and-test-windows:
    parameters:
      python-version:
        type: string

    executor:
      name: win/default

    environment:
      <<: *global-environment
      CIBW_PROJECT_REQUIRES_PYTHON: ~=<< parameters.python-version>>
      CIBW_ARCHS_WINDOWS: AMD64

    steps:
      - checkout
      - run-cibuildwheel

  deploy-all:
    docker:
      - image: cimg/python:3.9

    steps:
      - attach_workspace:
          at: dist

      - store_artifacts:
          path: ./dist

      - run:
          name: deploy
          command: |
            python -m venv env
            . env/bin/activate
            python -m pip install twine
            twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" --skip-existing ./dist/*

  # and configuration to work correctly is a pain. And since there is not
  # significant different between the linux/osx/windows code I think it
  # suffices to just do it once
  test-codecov:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_dev.txt
      - run: &unix-build
          name: build
          command: |
            . env/bin/activate
            python dwave/gate/simulator/operation_generation.py
            pip install .
      - run:
          name: run coverage
          command: |
            . env/bin/activate
            pytest tests/ --cov=dwave.gate
      - run:
          name: codecov
          command: |
            . env/bin/activate
            pip install codecov
            codecov

  test-sdist:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: install from sdist
          command: |
            python -m venv env
            . env/bin/activate
            pip install dist/dwave-gate*.tar.gz
      - run:
          name: run tests
          command: |
            . env/bin/activate
            pip install -r requirements_dev.txt
            pytest tests/

workflows:
  tests:
    jobs:
      - build-and-test-linux: &build
          matrix:
            parameters:
              python-version: &python-versions [3.7.9, 3.8.9, 3.9.4, 3.10.0, 3.11.0]
      - build-and-test-linux-aarch64:
          matrix:
            parameters:
              python-version: *python-versions
            exclude:
              - python-version: 3.7.9
      - build-sdist
      - build-and-test-osx: &build-and-test-osx
          matrix:
            parameters:
              python-version: *python-versions
              cibw-arch: [x86_64, arm64]
            exclude:
              - python-version: 3.7.9
                cibw-arch: arm64
      - build-and-test-windows: *build
      - test-codecov
      - test-sdist:
          requires:
            - build-sdist
  deploy:
    jobs:
      - build-and-test-linux: &deploy-build
          <<: *build
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - build-and-test-linux-aarch64:
          matrix:
            parameters:
              python-version: *python-versions
            exclude:
              - python-version: 3.7.9
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - build-and-test-osx:
          <<: *build-and-test-osx
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - build-sdist:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - build-and-test-windows: *deploy-build
      - deploy-all:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
          requires:
            - build-and-test-linux
            - build-and-test-linux-aarch64
            - build-and-test-osx
            - build-sdist
            - build-and-test-windows
